"""Added AI Asset table

Revision ID: 5cb8b949bb71
Revises: ea2679878e00
Create Date: 2025-05-22 10:18:45.292553

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import core.db_models.utils


# revision identifiers, used by Alembic.
revision: str = '5cb8b949bb71'
down_revision: Union[str, None] = 'ea2679878e00'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('ai_asset',
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('created_by', sa.String(length=255), nullable=True),
    sa.Column('updated_by', sa.String(length=255), nullable=True),
    sa.Column('uuid', sa.String(length=36), nullable=True),
    sa.Column('location', sa.String(length=255), nullable=True),
    sa.Column('owner', sa.String(length=255), nullable=False),
    sa.Column('asset_type', sa.String(length=255), nullable=False),
    sa.Column('source', sa.String(length=255), nullable=True),
    sa.Column('risk_score', sa.Integer(), nullable=True),
    sa.Column('risk_level', sa.String(), nullable=True),
    sa.Column('ai_model', sa.String(), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('meta_data', sa.JSON(), nullable=True),
    sa.Column('ai_application_id', sa.Integer(), nullable=True),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('status', sa.Integer(), nullable=False),
    sa.Column('create_time', sa.DateTime(), nullable=False),
    sa.Column('update_time', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_ai_asset_create_time'), 'ai_asset', ['create_time'], unique=False)
    op.create_index(op.f('ix_ai_asset_id'), 'ai_asset', ['id'], unique=False)
    op.create_index(op.f('ix_ai_asset_name'), 'ai_asset', ['name'], unique=True)
    op.create_index(op.f('ix_ai_asset_update_time'), 'ai_asset', ['update_time'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_ai_asset_update_time'), table_name='ai_asset')
    op.drop_index(op.f('ix_ai_asset_name'), table_name='ai_asset')
    op.drop_index(op.f('ix_ai_asset_id'), table_name='ai_asset')
    op.drop_index(op.f('ix_ai_asset_create_time'), table_name='ai_asset')
    op.drop_table('ai_asset')
    # ### end Alembic commands ###
